class SampleStruct < ActionWebService::Struct
	member 	:sample_date,             :time
	member	:temp,                    :float
	member	:temp_m,                  :float
	member	:dewpoint,                :float
	member	:dewpoint_m,              :float
	member	:pressure,                :float
	member	:pressure_m,              :float
	member	:bar_status,              :string
	member	:humidity,                :int
	member	:windspeed,               :int
	member	:windspeed_m,             :int
	member	:wind_direction,          :int
	member  :apparent_temp,           :int
	member  :apparent_temp_m,         :int
	member  :solar_radiation,         :int
	member  :rain_rate,               :float
	member  :rain_rate_m,             :float
	member  :daily_rain,              :float
	member  :daily_rain_m,            :float
	member  :monthly_rain,            :float
	member  :monthly_rain_m,          :float
	member  :yearly_rain,             :float
	member  :yearly_rain_m,           :float
	member  :storm_rain,              :float
	member  :storm_rain_m,            :float
	member  :ten_min_avg_wind,        :int
	member  :ten_min_avg_wind_m,      :int
	member  :is_raining,              :bool
  member  :inside_temperature,      :float
  member  :inside_temperature_m,    :float
  member  :inside_humidity,         :int
	member 	:sunrise,                 :time
	member 	:sunset,                  :time
	member  :uv,                      :int
end
