/*
 * Created on 02-Jan-2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package uk.me.jstott.jweatherstation;

/**
 * @author Jonathan Stott
 * @version 1.0
 * @since 1.0
 */
public class ForecastRules {
  /**
   * 
   * 
   * @since 1.0
   */
  public static final String[] RULES = {
      "Mostly clear and cooler.",
      "Mostly clear with little temperature change.",
      "Mostly clear for 12 hours with little temperature change.",
      "Mostly clear for 12 to 24 hours and cooler.",
      "Mostly clear with little temperature change.",
      "Partly cloudy and cooler.",
      "Partly cloudy with little temperature change.",
      "Partly cloudy with little temperature change.",
      "Mostly clear and warmer.",
      "Partly cloudy with little temperature change.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 24 to 48 hours.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds with little temperature change. Precipitation possible within 24 hours.",
      "Mostly clear with little temperature change.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds with little temperature change. Precipitation possible within 12 hours.",
      "Mostly clear with little temperature change.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 24 hours.",
      "Mostly clear and warmer. Increasing winds.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 hours. Increasing winds.",
      "Mostly clear and warmer. Increasing winds.",
      "Increasing clouds and warmer.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 hours. Increasing winds.",
      "Mostly clear and warmer. Increasing winds.",
      "Increasing clouds and warmer.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 hours. Increasing winds.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly clear and warmer. Precipitation possible within 48 hours.",
      "Mostly clear and warmer.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds with little temperature change. Precipitation possible within 24 to 48 hours.",
      "Increasing clouds with little temperature change.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 to 24 hours.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 to 24 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 to 24 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 6 to 12 hours.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 6 to 12 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 to 24 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation possible within 12 hours.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and warmer. Precipitation likley.",
      "Clearing and cooler. Precipitation ending within 6 hours.",
      "Partly cloudy with little temperature change.",
      "Clearing and cooler. Precipitation ending within 6 hours.",
      "Mostly clear with little temperature change.",
      "Clearing and cooler. Precipitation ending within 6 hours.",
      "Partly cloudy and cooler.",
      "Partly cloudy with little temperature change.",
      "Mostly clear and cooler.",
      "Clearing and cooler. Precipitation ending within 6 hours.",
      "Mostly clear with little temperature change.",
      "Clearing and cooler. Precipitation ending within 6 hours.",
      "Mostly clear and cooler.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds with little temperature change. Precipitation possible within 24 hours.",
      "Mostly cloudy and cooler. Precipitation continuing.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation likely.",
      "Mostly cloudy with little temperature change. Precipitation continuing.",
      "Mostly cloudy with little temperature change. Precipitation likely.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible and windy within 6 hours.",
      "Increasing clouds with little temperature change. Precipitation possible and windy within 6 hours.",
      "Mostly cloudy and cooler. Precipitation continuing. Increasing winds.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation likely. Increasing winds.",
      "Mostly cloudy with little temperature change. Precipitation continuing. Increasing winds.",
      "Mostly cloudy with little temperature change. Precipitation likely. Increasing winds.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 12 to 24 hours possible wind shift to the W, NW, or N.",
      "Increasing clouds with little temperature change. Precipitation possible within 12 to 24 hours possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 6 hours possible wind shift to the W, NW, or N.",
      "Increasing clouds with little temperature change. Precipitation possible within 6 hours possible wind shift to the W, NW, or N.",
      "Mostly cloudy and cooler. Precipitation ending within 12 hours possible wind shift to the W, NW, or N.",
      "Mostly cloudy and cooler. Possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation ending within 12 hours possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Possible wind shift to the W, NW, or N.",
      "Mostly cloudy and cooler. Precipitation ending within 12 hours possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation possible within 24 hours possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation ending within 12 hours possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation possible within 24 hours possible wind shift to the W, NW, or N.",
      "Clearing, cooler and windy. Precipitation ending within 6 hours.",
      "Clearing, cooler and windy.",
      "Mostly cloudy and cooler. Precipitation ending within 6 hours. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy and cooler. Windy with possible wind shift o the W, NW, or N.",
      "Clearing, cooler and windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy with little temperature change. Precipitation possible within 12 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 12 hours, possibly heavy at times. Windy.",
      "Mostly cloudy and cooler. Precipitation ending within 6 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation possible within 12 hours. Windy.",
      "Mostly cloudy and cooler. Precipitation ending in 12 to 24 hours.",
      "Mostly cloudy and cooler.",
      "Mostly cloudy and cooler. Precipitation continuing, possible heavy at times. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation possible within 6 to 12 hours. Windy.",
      "Mostly cloudy with little temperature change. Precipitation continuing, possibly heavy at times. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy with little temperature change. Precipitation possible within 6 to 12 hours. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds with little temperature change. Precipitation possible within 12 hours, possibly heavy at times. Windy.",
      "Mostly cloudy and cooler. Windy.",
      "Mostly cloudy and cooler. Precipitation continuing, possibly heavy at times. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation likely, possibly heavy at times. Windy.",
      "Mostly cloudy with little temperature change. Precipitation continuing, possibly heavy at times. Windy.",
      "Mostly cloudy with little temperature change. Precipitation likely, possibly heavy at times. Windy.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 6 hours. Windy.",
      "Increasing clouds with little temperature change. Precipitation possible within 6 hours. Windy",
      "Increasing clouds and cooler. Precipitation continuing. Windy with possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation likely. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation continuing. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation likely. Windy with possible wind shift to the W, NW, or N.",
      "Increasing clouds and cooler. Precipitation possible within 6 hours. Windy with possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 6 hours possible wind shift to the W, NW, or N.",
      "Increasing clouds with little temperature change. Precipitation possible within 6 hours. Windy with possible wind shift to the W, NW, or N.",
      "Increasing clouds with little temperature change. Precipitation possible within 6 hours possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 6 hours. Windy with possible wind shift to the W, NW, or N.",
      "Increasing clouds with little temperature change. Precipitation possible within 6 hours. Windy with possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Increasing clouds and cooler. Precipitation possible within 12 to 24 hours. Windy with possible wind shift to the W, NW, or N.",
      "Increasing clouds with little temperature change. Precipitation possible within 12 to 24 hours. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy and cooler. Precipitation possibly heavy at times and ending within 12 hours. Windy with possible wind shift to the W, NW, or N.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation possible within 6 to 12 hours, possibly heavy at times. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation ending within 12 hours. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation possible within 6 to 12 hours, possibly heavy at times. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy and cooler. Precipitation continuing.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation likely. Windy with possible wind shift to the W, NW, or N.",
      "Mostly cloudy with little temperature change. Precipitation continuing.",
      "Mostly cloudy with little temperature change. Precipitation likely.",
      "Partly cloudy with little temperature change.",
      "Mostly clear with little temperature change.",
      "Mostly cloudy and cooler. Precipitation possible within 12 hours, possibly heavy at times. Windy.",
      "FORECAST REQUIRES 3 HOURS OF RECENT DATA", "Mostly clear and cooler.",
      "Mostly clear and cooler.", "Mostly clear and cooler." };
}
