# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "archive_records", :force => true do |t|
    t.column "date", :datetime, :null => false
    t.column "location", :string, :limit => 10, :default => "", :null => false
    t.column "outside_temp", :float, :limit => 4
    t.column "high_outside_temp", :float, :limit => 4
    t.column "low_outside_temp", :float, :limit => 4
    t.column "pressure", :float, :limit => 5
    t.column "outside_humidity", :integer, :limit => 6
    t.column "rainfall", :float, :limit => 5
    t.column "high_rain_rate", :float, :limit => 6
    t.column "average_wind_speed", :integer, :limit => 6
    t.column "high_wind_speed", :integer, :limit => 6
    t.column "direction_of_high_wind_speed", :integer, :limit => 6
    t.column "prevailing_wind_direction", :integer, :limit => 6
    t.column "inside_temp", :float, :limit => 4
    t.column "average_dewpoint", :float, :limit => 4
    t.column "average_apparent_temp", :integer, :limit => 6
    t.column "inside_humidity", :integer, :limit => 6
    t.column "solar_radiation", :integer
    t.column "average_uv_index", :integer
    t.column "et", :integer
    t.column "high_solar_radation", :integer
    t.column "high_uv_index", :integer
    t.column "forecastRule", :integer
    t.column "leaf_temp_1", :integer
    t.column "leaf_temp_2", :integer
    t.column "leaf_wetness1", :integer
    t.column "leaf_wetness2", :integer
    t.column "soil_temp1", :integer
    t.column "soil_temp2", :integer
    t.column "soil_temp3", :integer
    t.column "soil_temp4", :integer
    t.column "extra_humidity1", :integer
    t.column "extra_humidity2", :integer
    t.column "extra_temp1", :integer
    t.column "extra_temp2", :integer
    t.column "extra_temp3", :integer
    t.column "soil_moisture1", :integer
    t.column "soil_moisture2", :integer
    t.column "soil_moisture3", :integer
    t.column "soil_moisture4", :integer
    t.column "number_of_wind_samples", :integer
    t.column "download_record_type", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "archive_records", ["date", "location"], :name => "date_loc", :unique => true
  add_index "archive_records", ["date"], :name => "dates"
  add_index "archive_records", ["location"], :name => "locations"

  create_table "current_conditions", :force => true do |t|
    t.column "location", :string, :limit => 10, :default => "", :null => false
    t.column "sample_date", :datetime
    t.column "outside_temperature", :float, :limit => 4
    t.column "outside_humidity", :integer, :limit => 6
    t.column "dewpoint", :float, :limit => 4
    t.column "apparent_temp", :integer, :limit => 6
    t.column "pressure", :float, :limit => 5
    t.column "bar_status", :string, :limit => 25
    t.column "windspeed", :integer, :limit => 6
    t.column "wind_direction", :integer, :limit => 6
    t.column "is_raining", :boolean
    t.column "rain_rate", :float, :limit => 5
    t.column "ten_min_avg_wind", :integer, :limit => 6
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "current_conditions", ["location"], :name => "locations", :unique => true

  create_table "statuses", :force => true do |t|
    t.column "location", :string, :limit => 10, :default => "", :null => false
    t.column "sample_date", :datetime
    t.column "archive_date", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "statuses", ["location"], :name => "locations", :unique => true

end
